<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MemoryPack.Core/MemoryPack.Core.csproj" />
    <ProjectReference Include="../../src/MemoryPack.Generator/MemoryPack.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../MemoryPack.ExternalUnionModels/MemoryPack.ExternalUnionModels.csproj" />
  </ItemGroup>
</Project>
