<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);CS1591;CA2255</NoWarn>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- NuGet -->
        <IsPackable>true</IsPackable>
        <PackageId>SharpPack.Streaming</PackageId>
        <PackageTags>serializer;streaming;pipelines;zero-copy;memorypack-compatible</PackageTags>
        <Description>PipeReader, PipeWriter, and framed streaming support for SharpPack.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SharpPack.Core\SharpPack.Core.csproj" />
    </ItemGroup>

</Project>
