#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

tool_project="tools/SharpPack.Baselines/SharpPack.Baselines.csproj"
api_file="src/SharpPack.Core/SharpPackSerializerRuntimeOptions.cs"
emitter_file="src/SharpPack.Generator/SharpPackGenerator.Emitter.cs"

restore_files() {
  git checkout -- "$api_file" "$emitter_file"
}
trap restore_files EXIT

replace_once() {
  local path="$1"
  local old="$2"
  local new="$3"
  python3 - "$path" "$old" "$new" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
old = sys.argv[2]
new = sys.argv[3]
text = path.read_text()
count = text.count(old)
if count != 1:
    raise SystemExit(f"expected exactly one occurrence in {path}, found {count}")
path.write_text(text.replace(old, new, 1))
PY
}

expect_verify_failure() {
  local label="$1"
  local expected_fragment="$2"
  local output
  local status

  set +e
  output="$(dotnet run --project "$tool_project" -c Release --no-restore -- verify 2>&1)"
  status=$?
  set -e

  if [[ $status -eq 0 ]]; then
    echo "$label characterization unexpectedly passed verification" >&2
    exit 1
  fi

  if ! grep -Fq "$expected_fragment" <<<"$output"; then
    echo "$label characterization failed for an unexpected reason" >&2
    echo "$output" >&2
    exit 1
  fi

  echo "Characterized $label: verification rejected the deliberate mutation."
}

replace_once   "$api_file"   'public int ThreadBufferSize { get; init; } = DefaultThreadBufferSize;'   'public int ThreadBufferSize { get; set; } = DefaultThreadBufferSize;'
expect_verify_failure   "public API signature gate"   "Baseline mismatch: eng/baselines/public-api/SharpPack.Core.txt"

git checkout -- "$api_file"
dotnet build src/SharpPack.Core/SharpPack.Core.csproj -c Release --no-incremental --no-restore >/dev/null

replace_once   "$emitter_file"   '// <auto-generated/>'   '// <auto-generated baseline-characterization/>'
expect_verify_failure   "generated-source snapshot gate"   "Baseline mismatch: eng/baselines/generated/representative.g.cs.txt"

git checkout -- "$emitter_file"
dotnet build src/SharpPack.Generator/SharpPack.Generator.csproj -c Release --no-incremental --no-restore >/dev/null

dotnet run --project "$tool_project" -c Release --no-restore -- verify
trap - EXIT
