using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace MemoryPack.Generator;

partial class MemoryPackGenerator
{
    static void GenerateExternalUnionTargetFactories(
        ImmutableArray<TypeDeclarationSyntax> declarations,
        Compilation compilation,
        IGeneratorContext context)
    {
        if (declarations.IsDefaultOrEmpty)
        {
            return;
        }

        var references = new ReferenceSymbols(compilation);
        var groups =
            new Dictionary<INamedTypeSymbol, List<ExternalUnionFactoryEntry>>(
                SymbolEqualityComparer.Default);

        foreach (var declaration in declarations)
        {
            var semanticModel =
                compilation.GetSemanticModel(declaration.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(
                    declaration,
                    context.CancellationToken) is not INamedTypeSymbol formatter)
            {
                continue;
            }

            var attribute = formatter.GetAttribute(
                references.MemoryPackUnionFormatterAttribute);
            if (attribute?.ConstructorArguments[0].Value is not
                INamedTypeSymbol union)
            {
                continue;
            }

            var target = union.OriginalDefinition;
            if (!SymbolEqualityComparer.Default.Equals(
                    target.ContainingAssembly,
                    formatter.ContainingAssembly) ||
                target.DeclaringSyntaxReferences.Length == 0 ||
                !IsPartialTarget(target))
            {
                continue;
            }

            if (!groups.TryGetValue(target, out var entries))
            {
                entries = new List<ExternalUnionFactoryEntry>();
                groups.Add(target, entries);
            }

            entries.Add(new ExternalUnionFactoryEntry(formatter, union));
        }

        foreach (var group in groups.OrderBy(static group =>
                     group.Key.FullyQualifiedToString(),
                     StringComparer.Ordinal))
        {
            EmitExternalUnionTargetFactory(
                group.Key,
                group.Value,
                context);
        }
    }

    static bool IsPartialTarget(INamedTypeSymbol target)
    {
        for (var current = target;
             current is not null;
             current = current.ContainingType)
        {
            if (current.DeclaringSyntaxReferences.Any(static reference =>
                    reference.GetSyntax() is not
                        TypeDeclarationSyntax declaration ||
                    !declaration.Modifiers.Any(static modifier =>
                        modifier.IsKind(SyntaxKind.PartialKeyword))))
            {
                return false;
            }
        }

        return true;
    }

    static void EmitExternalUnionTargetFactory(
        INamedTypeSymbol target,
        List<ExternalUnionFactoryEntry> entries,
        IGeneratorContext context)
    {
        var compatibleEntries = entries
            .Where(entry => CanConstructFormatter(target, entry))
            .OrderBy(static entry => IsOpenPattern(entry.Union) ? 1 : 0)
            .ThenBy(static entry =>
                entry.Union.FullyQualifiedToString(),
                StringComparer.Ordinal)
            .ThenBy(static entry =>
                entry.Formatter.FullyQualifiedToString(),
                StringComparer.Ordinal)
            .ToArray();
        if (compatibleEntries.Length == 0)
        {
            return;
        }

        var targetType = ConstructedTargetName(target);
        var containingTypes = new List<INamedTypeSymbol>();
        for (var current = target.ContainingType;
             current is not null;
             current = current.ContainingType)
        {
            containingTypes.Add(current.OriginalDefinition);
        }
        containingTypes.Reverse();

        var sb = new StringBuilder();
        sb.AppendLine("""
// <auto-generated/>
#nullable enable
#pragma warning disable CS0162
#pragma warning disable CS0618
""");

        var ns = target.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            if (context.IsCSharp10OrGreater())
            {
                sb.AppendLine($"namespace {ns};");
            }
            else
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }
        }

        foreach (var containingType in containingTypes)
        {
            sb.AppendLine(TypeMeta.EmitPartialTypeDeclaration(containingType));
            sb.AppendLine(TypeMeta.EmitTypeParameterConstraints(
                containingType.TypeParameters));
            sb.AppendLine("{");
        }

        sb.AppendLine("[global::MemoryPack.Internal.Preserve]");
        sb.AppendLine(TypeMeta.EmitPartialTypeDeclaration(target) + " :");
        sb.AppendLine(
            $"    global::MemoryPack.IMemoryPackFormatterFactory<{targetType}>");
        sb.AppendLine(TypeMeta.EmitTypeParameterConstraints(
            target.TypeParameters));
        sb.AppendLine("{");
        sb.AppendLine(
            $"    static global::MemoryPack.MemoryPackFormatter<{targetType}>");
        sb.AppendLine(
            $"        global::MemoryPack.IMemoryPackFormatterFactory<{targetType}>.CreateFormatter()");
        sb.AppendLine("    {");

        var emittedPatterns = new HashSet<string>(StringComparer.Ordinal);
        ExternalUnionFactoryEntry? openEntry = null;
        foreach (var entry in compatibleEntries)
        {
            if (IsOpenPattern(entry.Union))
            {
                openEntry ??= entry;
                continue;
            }

            var condition = EmitPatternCondition(target, entry.Union);
            if (!emittedPatterns.Add(condition))
            {
                continue;
            }

            sb.AppendLine($"        if ({condition})");
            sb.AppendLine("        {");
            sb.AppendLine(
                $"            return (global::MemoryPack.MemoryPackFormatter<{targetType}>)(object)new {ConstructedFormatterName(target, entry)}();");
            sb.AppendLine("        }");
        }

        if (openEntry is { } fallback)
        {
            sb.AppendLine(
                $"        return new {ConstructedFormatterName(target, fallback)}();");
        }
        else
        {
            sb.AppendLine(
                $"        throw new global::MemoryPack.MemoryPackSerializationException(\"No generated external union formatter is available for \" + typeof({targetType}).FullName + \".\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        for (var i = containingTypes.Count - 1; i >= 0; i--)
        {
            sb.AppendLine("}");
        }

        if (!ns.IsGlobalNamespace && !context.IsCSharp10OrGreater())
        {
            sb.AppendLine("}");
        }

        var hintName = target.FullyQualifiedToString()
            .Replace("global::", "")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "");
        context.AddSource(
            $"{hintName}.MemoryPackExternalUnionFactory.g.cs",
            sb.ToString());
    }

    static bool CanConstructFormatter(
        INamedTypeSymbol target,
        ExternalUnionFactoryEntry entry)
    {
        if (!target.IsGenericType)
        {
            return entry.Formatter.TypeParameters.Length == 0;
        }

        if (IsOpenPattern(entry.Union))
        {
            return entry.Formatter.TypeParameters.Length ==
                target.TypeParameters.Length;
        }

        return entry.Formatter.TypeParameters.Length == 0 &&
            entry.Union.TypeArguments.All(static argument =>
                argument is not ITypeParameterSymbol);
    }

    static bool IsOpenPattern(INamedTypeSymbol union)
        => !union.IsGenericType ||
           union.IsUnboundGenericType ||
           (union.IsGenericType &&
            union.TypeArguments.All(static argument =>
                argument is ITypeParameterSymbol));

    static string ConstructedTargetName(INamedTypeSymbol target)
    {
        if (!target.IsGenericType)
        {
            return target.FullyQualifiedToString();
        }

        var typeArguments = string.Join(
            ", ",
            target.TypeParameters.Select(static parameter => parameter.Name));
        var definition = target.ConstructUnboundGenericType()
            .FullyQualifiedToString();
        return definition.Replace("<>", $"<{typeArguments}>");
    }

    static string ConstructedFormatterName(
        INamedTypeSymbol target,
        ExternalUnionFactoryEntry entry)
    {
        if (entry.Formatter.TypeParameters.Length == 0)
        {
            return entry.Formatter.Name;
        }

        var typeArguments = string.Join(
            ", ",
            target.TypeParameters.Select(static parameter => parameter.Name));
        return $"{entry.Formatter.Name}<{typeArguments}>";
    }

    static string EmitPatternCondition(
        INamedTypeSymbol target,
        INamedTypeSymbol union)
    {
        var conditions = target.TypeParameters
            .Zip(
                union.TypeArguments,
                static (parameter, argument) =>
                    $"typeof({parameter.Name}) == typeof({argument.FullyQualifiedToString()})");
        return string.Join(" && ", conditions);
    }

    readonly struct ExternalUnionFactoryEntry
    {
        public INamedTypeSymbol Formatter { get; }
        public INamedTypeSymbol Union { get; }

        public ExternalUnionFactoryEntry(
            INamedTypeSymbol formatter,
            INamedTypeSymbol union)
        {
            Formatter = formatter;
            Union = union;
        }
    }
}
