using MemoryPack.Formatters;
using System.Collections;
using System.Globalization;
using System.Text;
using System.Numerics;

namespace MemoryPack;

internal static partial class FormatterResolver
{
    internal static object? CreateWellKnownFormatter(Type type)
    {
        if (type == typeof(SByte)) return new UnmanagedFormatter<SByte>();
        if (type == typeof(SByte[])) return new UnmanagedArrayFormatter<SByte>();
        if (type == typeof(SByte?)) return new NullableFormatter<SByte>();
        if (type == typeof(Byte)) return new UnmanagedFormatter<Byte>();
        if (type == typeof(Byte[])) return new UnmanagedArrayFormatter<Byte>();
        if (type == typeof(Byte?)) return new NullableFormatter<Byte>();
        if (type == typeof(Int16)) return new UnmanagedFormatter<Int16>();
        if (type == typeof(Int16[])) return new UnmanagedArrayFormatter<Int16>();
        if (type == typeof(Int16?)) return new NullableFormatter<Int16>();
        if (type == typeof(UInt16)) return new UnmanagedFormatter<UInt16>();
        if (type == typeof(UInt16[])) return new UnmanagedArrayFormatter<UInt16>();
        if (type == typeof(UInt16?)) return new NullableFormatter<UInt16>();
        if (type == typeof(Int32)) return new UnmanagedFormatter<Int32>();
        if (type == typeof(Int32[])) return new UnmanagedArrayFormatter<Int32>();
        if (type == typeof(Int32?)) return new NullableFormatter<Int32>();
        if (type == typeof(UInt32)) return new UnmanagedFormatter<UInt32>();
        if (type == typeof(UInt32[])) return new UnmanagedArrayFormatter<UInt32>();
        if (type == typeof(UInt32?)) return new NullableFormatter<UInt32>();
        if (type == typeof(Int64)) return new UnmanagedFormatter<Int64>();
        if (type == typeof(Int64[])) return new UnmanagedArrayFormatter<Int64>();
        if (type == typeof(Int64?)) return new NullableFormatter<Int64>();
        if (type == typeof(UInt64)) return new UnmanagedFormatter<UInt64>();
        if (type == typeof(UInt64[])) return new UnmanagedArrayFormatter<UInt64>();
        if (type == typeof(UInt64?)) return new NullableFormatter<UInt64>();
        if (type == typeof(Char)) return new UnmanagedFormatter<Char>();
        if (type == typeof(Char[])) return new UnmanagedArrayFormatter<Char>();
        if (type == typeof(Char?)) return new NullableFormatter<Char>();
        if (type == typeof(Single)) return new UnmanagedFormatter<Single>();
        if (type == typeof(Single[])) return new UnmanagedArrayFormatter<Single>();
        if (type == typeof(Single?)) return new NullableFormatter<Single>();
        if (type == typeof(Double)) return new UnmanagedFormatter<Double>();
        if (type == typeof(Double[])) return new UnmanagedArrayFormatter<Double>();
        if (type == typeof(Double?)) return new NullableFormatter<Double>();
        if (type == typeof(Decimal)) return new UnmanagedFormatter<Decimal>();
        if (type == typeof(Decimal[])) return new UnmanagedArrayFormatter<Decimal>();
        if (type == typeof(Decimal?)) return new NullableFormatter<Decimal>();
        if (type == typeof(Boolean)) return new UnmanagedFormatter<Boolean>();
        if (type == typeof(Boolean[])) return new UnmanagedArrayFormatter<Boolean>();
        if (type == typeof(Boolean?)) return new NullableFormatter<Boolean>();
        if (type == typeof(IntPtr)) return new UnmanagedFormatter<IntPtr>();
        if (type == typeof(IntPtr[])) return new UnmanagedArrayFormatter<IntPtr>();
        if (type == typeof(IntPtr?)) return new NullableFormatter<IntPtr>();
        if (type == typeof(UIntPtr)) return new UnmanagedFormatter<UIntPtr>();
        if (type == typeof(UIntPtr[])) return new UnmanagedArrayFormatter<UIntPtr>();
        if (type == typeof(UIntPtr?)) return new NullableFormatter<UIntPtr>();
        if (type == typeof(DateTime)) return new UnmanagedFormatter<DateTime>();
        if (type == typeof(DateTime[])) return new UnmanagedArrayFormatter<DateTime>();
        if (type == typeof(DateTime?)) return new NullableFormatter<DateTime>();
        if (type == typeof(DateTimeOffset)) return new UnmanagedFormatter<DateTimeOffset>();
        if (type == typeof(DateTimeOffset[])) return new UnmanagedArrayFormatter<DateTimeOffset>();
        if (type == typeof(DateTimeOffset?)) return new NullableFormatter<DateTimeOffset>();
        if (type == typeof(TimeSpan)) return new UnmanagedFormatter<TimeSpan>();
        if (type == typeof(TimeSpan[])) return new UnmanagedArrayFormatter<TimeSpan>();
        if (type == typeof(TimeSpan?)) return new NullableFormatter<TimeSpan>();
        if (type == typeof(Guid)) return new UnmanagedFormatter<Guid>();
        if (type == typeof(Guid[])) return new UnmanagedArrayFormatter<Guid>();
        if (type == typeof(Guid?)) return new NullableFormatter<Guid>();
        if (type == typeof(Complex)) return new UnmanagedFormatter<Complex>();
        if (type == typeof(Complex[])) return new UnmanagedArrayFormatter<Complex>();
        if (type == typeof(Complex?)) return new NullableFormatter<Complex>();
        if (type == typeof(Plane)) return new UnmanagedFormatter<Plane>();
        if (type == typeof(Plane[])) return new UnmanagedArrayFormatter<Plane>();
        if (type == typeof(Plane?)) return new NullableFormatter<Plane>();
        if (type == typeof(Quaternion)) return new UnmanagedFormatter<Quaternion>();
        if (type == typeof(Quaternion[])) return new UnmanagedArrayFormatter<Quaternion>();
        if (type == typeof(Quaternion?)) return new NullableFormatter<Quaternion>();
        if (type == typeof(Matrix3x2)) return new UnmanagedFormatter<Matrix3x2>();
        if (type == typeof(Matrix3x2[])) return new UnmanagedArrayFormatter<Matrix3x2>();
        if (type == typeof(Matrix3x2?)) return new NullableFormatter<Matrix3x2>();
        if (type == typeof(Matrix4x4)) return new UnmanagedFormatter<Matrix4x4>();
        if (type == typeof(Matrix4x4[])) return new UnmanagedArrayFormatter<Matrix4x4>();
        if (type == typeof(Matrix4x4?)) return new NullableFormatter<Matrix4x4>();
        if (type == typeof(Vector2)) return new UnmanagedFormatter<Vector2>();
        if (type == typeof(Vector2[])) return new UnmanagedArrayFormatter<Vector2>();
        if (type == typeof(Vector2?)) return new NullableFormatter<Vector2>();
        if (type == typeof(Vector3)) return new UnmanagedFormatter<Vector3>();
        if (type == typeof(Vector3[])) return new UnmanagedArrayFormatter<Vector3>();
        if (type == typeof(Vector3?)) return new NullableFormatter<Vector3>();
        if (type == typeof(Vector4)) return new UnmanagedFormatter<Vector4>();
        if (type == typeof(Vector4[])) return new UnmanagedArrayFormatter<Vector4>();
        if (type == typeof(Vector4?)) return new NullableFormatter<Vector4>();
        if (type == typeof(Rune)) return new UnmanagedFormatter<Rune>();
        if (type == typeof(Rune[])) return new UnmanagedArrayFormatter<Rune>();
        if (type == typeof(Rune?)) return new NullableFormatter<Rune>();
        if (type == typeof(DateOnly)) return new UnmanagedFormatter<DateOnly>();
        if (type == typeof(DateOnly[])) return new UnmanagedArrayFormatter<DateOnly>();
        if (type == typeof(DateOnly?)) return new NullableFormatter<DateOnly>();
        if (type == typeof(TimeOnly)) return new UnmanagedFormatter<TimeOnly>();
        if (type == typeof(TimeOnly[])) return new UnmanagedArrayFormatter<TimeOnly>();
        if (type == typeof(TimeOnly?)) return new NullableFormatter<TimeOnly>();
        if (type == typeof(Half)) return new UnmanagedFormatter<Half>();
        if (type == typeof(Half[])) return new UnmanagedArrayFormatter<Half>();
        if (type == typeof(Half?)) return new NullableFormatter<Half>();
        if (type == typeof(Int128)) return new UnmanagedFormatter<Int128>();
        if (type == typeof(Int128[])) return new UnmanagedArrayFormatter<Int128>();
        if (type == typeof(Int128?)) return new NullableFormatter<Int128>();
        if (type == typeof(UInt128)) return new UnmanagedFormatter<UInt128>();
        if (type == typeof(UInt128[])) return new UnmanagedArrayFormatter<UInt128>();
        if (type == typeof(UInt128?)) return new NullableFormatter<UInt128>();
        if (type == typeof(String)) return new StringFormatter();
        if (type == typeof(String[])) return new ArrayFormatter<String>();
        if (type == typeof(Version)) return new VersionFormatter();
        if (type == typeof(Version[])) return new ArrayFormatter<Version>();
        if (type == typeof(Uri)) return new UriFormatter();
        if (type == typeof(Uri[])) return new ArrayFormatter<Uri>();
        if (type == typeof(TimeZoneInfo)) return new TimeZoneInfoFormatter();
        if (type == typeof(TimeZoneInfo[])) return new ArrayFormatter<TimeZoneInfo>();
        if (type == typeof(BigInteger)) return new BigIntegerFormatter();
        if (type == typeof(BigInteger[])) return new ArrayFormatter<BigInteger>();
        if (type == typeof(BitArray)) return new BitArrayFormatter();
        if (type == typeof(BitArray[])) return new ArrayFormatter<BitArray>();
        if (type == typeof(StringBuilder)) return new StringBuilderFormatter();
        if (type == typeof(StringBuilder[])) return new ArrayFormatter<StringBuilder>();
        if (type == typeof(Type)) return new TypeFormatter();
        if (type == typeof(Type[])) return new ArrayFormatter<Type>();
        if (type == typeof(CultureInfo)) return new CultureInfoFormatter();
        if (type == typeof(CultureInfo[])) return new ArrayFormatter<CultureInfo>();
        return null;
    }
}
