using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;

namespace SharpPack.Generator;

partial class SharpPackGenerator
{
    static void Generate(TypeDeclarationSyntax syntax, Compilation compilation, string? serializationInfoLogDirectoryPath, IGeneratorContext context)
    {
        var semanticModel = compilation.GetSemanticModel(syntax.SyntaxTree);

        var typeSymbol = semanticModel.GetDeclaredSymbol(syntax, context.CancellationToken);
        if (typeSymbol == null)
        {
            return;
        }

        // verify is partial
        if (!IsPartial(syntax))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.MustBePartial, syntax.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        if (IsNested(syntax) && !IsNestedContainingTypesPartial(syntax))
        {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticDescriptors.NestedContainingTypesMustBePartial, syntax.Identifier.GetLocation(), typeSymbol.Name));
            return;
        }

        var reference = new ReferenceSymbols(compilation);

        var unionSymbol = default(INamedTypeSymbol);
        var unionFormatterAttr = typeSymbol.GetAttribute(reference.SharpPackUnionFormatterAttribute);
        if (unionFormatterAttr != null)
        {
            // change symbol
            unionSymbol = unionFormatterAttr.ConstructorArguments[0].Value as INamedTypeSymbol;
            if (unionSymbol == null) return;
        }
        var unionFormatter = (unionSymbol != null);

        var typeMeta = new TypeMeta(typeSymbol, reference);
        if (unionFormatter)
        {
            // replace original symbol
            typeMeta.Symbol = unionSymbol!;
        }

        if (!unionFormatter && !typeMeta.IsUnion && typeMeta.GenerateType == GenerateType.NoGenerate)
        {
            return;
        }

        // ReportDiagnostic when validate failed.
        if (!typeMeta.Validate(syntax, context, unionFormatter))
        {
            return;
        }

        var fullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace("<", "_")
            .Replace(">", "_");

        var sb = new StringBuilder();

        sb.AppendLine(@"
// <auto-generated/>
#nullable enable
#pragma warning disable CS0108 // hides inherited member
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0164 // This label has not been referenced
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619
#pragma warning disable CS8620
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method
#pragma warning disable CS8765 // Nullability of type of parameter
#pragma warning disable CS9074 // The 'scoped' modifier of parameter doesn't match overridden or implemented member
#pragma warning disable CA1050 // Declare types in namespaces.

using System;
using SharpPack;
");

        var ns = typeMeta.Symbol.ContainingNamespace;
        if (!ns.IsGlobalNamespace)
        {
            if (context.IsCSharp10OrGreater())
            {
                sb.AppendLine($"namespace {ns};");
            }
            else
            {
                sb.AppendLine($"namespace {ns} {{");
            }
        }
        sb.AppendLine();

        // Write document comment as remarks
        if (typeMeta.GenerateType is GenerateType.Object or GenerateType.VersionTolerant or GenerateType.CircularReference)
        {
            BuildDebugInfo(sb, typeMeta, true);

            // also output to log
            if (serializationInfoLogDirectoryPath != null)
            {
                try
                {
                    if (!Directory.Exists(serializationInfoLogDirectoryPath))
                    {
                        Directory.CreateDirectory(serializationInfoLogDirectoryPath);
                    }
                    var logSw = new StringBuilder();
                    BuildDebugInfo(logSw, typeMeta, false);
                    var message = logSw.ToString();

                    File.WriteAllText(Path.Combine(serializationInfoLogDirectoryPath, $"{fullType}.txt"), message, new UTF8Encoding(false));
                }
                catch (Exception ex)
                {
                    Trace.WriteLine(ex.ToString());
                }
            }
        }

        // emit type info
        if (unionFormatter)
        {
            typeMeta.EmitUnionFormatterTemplate(sb, context, typeSymbol);
        }
        else
        {
            typeMeta.Emit(sb, context);
        }

        if (!ns.IsGlobalNamespace && !context.IsCSharp10OrGreater())
        {
            sb.AppendLine($"}}");
        }

        var code = sb.ToString();
        context.AddSource($"{fullType}.SharpPackFormatter.g.cs", code);
    }

    static bool IsPartial(TypeDeclarationSyntax typeDeclaration)
    {
        return typeDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));
    }

    static bool IsNestedContainingTypesPartial(TypeDeclarationSyntax typeDeclaration)
    {
        if (typeDeclaration.Parent is TypeDeclarationSyntax parentTypeDeclaration)
        {
            if (!IsPartial(parentTypeDeclaration))
                return false;

            return IsNestedContainingTypesPartial(parentTypeDeclaration);
        }
        else
        {
            return true;
        }
    }

    static bool IsNested(TypeDeclarationSyntax typeDeclaration)
    {
        return typeDeclaration.Parent is TypeDeclarationSyntax;
    }

    static void BuildDebugInfo(StringBuilder sb, TypeMeta type, bool xmlDocument)
    {
        string WithEscape(ISymbol symbol)
        {
            var str = symbol.FullyQualifiedToString().Replace("global::", "");
            if (xmlDocument)
            {
                return str.Replace("<", "&lt;").Replace(">", "&gt;");
            }
            else
            {
                return str;
            }
        }

        if (!xmlDocument)
        {
            if (type.IsUnmanagedType)
            {
                sb.Append("GenerateType unmanaged ");
            }
            else
            {
                sb.Append("GenerateType " + type.GenerateType.ToString() + " ");
            }
            sb.AppendLine(WithEscape(type.Symbol));
            sb.AppendLine("---");
        }
        else
        {
            sb.AppendLine("/// <remarks>");
            if (type.IsUnmanagedType)
            {
                sb.AppendLine("/// SharpPack GenerateType: unmanaged<br/>");
            }
            else
            {
                sb.AppendLine("/// SharpPack GenerateType: " + type.GenerateType.ToString() + "<br/>");
            }
            sb.AppendLine("/// <code>");
        }

        foreach (var item in type.Members)
        {
            if (xmlDocument)
            {
                sb.Append("/// <b>");
            }

            sb.Append(WithEscape(item.MemberType));
            if (xmlDocument)
            {
                sb.Append("</b>");
            }

            sb.Append(" ");
            sb.Append(item.Name);

            if (xmlDocument)
            {
                sb.AppendLine("<br/>");
            }
            else
            {
                sb.AppendLine();
            }
        }
        if (xmlDocument)
        {
            sb.AppendLine("/// </code>");
            sb.AppendLine("/// </remarks>");
        }
    }
}

public partial class TypeMeta
{
    public void Emit(StringBuilder writer, IGeneratorContext context)
    {
        if (IsUnion)
        {
            writer.AppendLine(EmitUnionTemplate(context));
            return;
        }

        if (GenerateType == GenerateType.Collection)
        {
            writer.AppendLine(EmitGenericCollectionTemplate(context));
            return;
        }

        var serializeBody = "";
        var deserializeBody = "";
        var formatterOverrideMethods = "";
        var contextFormatterTypeName = "__SharpPackContextFormatter";
        while (Symbol.GetAllMembers().Any(
                   member => member.Name == contextFormatterTypeName) ||
               Symbol.TypeParameters.Any(
                   parameter => parameter.Name == contextFormatterTypeName))
        {
            contextFormatterTypeName += "_";
        }
        if (IsUnmanagedType)
        {
            serializeBody = $$"""
        writer.WriteUnmanaged(value);
""";
            deserializeBody = $$"""
        reader.ReadUnmanaged(out value);
""";
        }
        else
        {
            var originalMembers = Members;
            if (GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference)
            {
                // for emit time, replace padded empty
                if (Members.Length != 0)
                {
                    var maxOrder = Members.Max(x => x.Order);
                    var tempMembers = new MemberMeta[maxOrder + 1];
                    for (int i = 0; i <= maxOrder; i++)
                    {
                        tempMembers[i] = Members.FirstOrDefault(x => x.Order == i) ?? MemberMeta.CreateEmpty(i);
                    }
                    Members = tempMembers;
                }
            }

            serializeBody = EmitSerializeBody();
            deserializeBody = EmitDeserializeBody();
            formatterOverrideMethods = EmitFormatterOverrideMethods(
                contextFormatterTypeName);

            Members = originalMembers;
        }

        var classOrStructOrRecord = (IsRecord, IsValueType) switch
        {
            (true, true) => "record struct",
            (true, false) => "record",
            (false, true) => "struct",
            (false, false) => "class",
        };

        var containingTypes = new List<INamedTypeSymbol>();
        var containingType = Symbol.ContainingType;
        while (containingType is not null)
        {
            containingTypes.Add(containingType);
            containingType = containingType.ContainingType;
        }
        containingTypes.Reverse();

        var nullable = IsValueType ? "" : "?";

        var staticSharpPackableMethod =
            $"static void ISharpPackable<{TypeName}>.";
        const string scopedRef = "scoped ref";
        const string constraint = "";
        var fixedSizeInterface = "";
        var fixedSizeMethod = "";
        var exactSizeInterface = "";
        var exactSizeMethod = "";
        var fixedSize = Members.All(x =>
            x.Kind is MemberKind.Unmanaged
                or MemberKind.Enum
                or MemberKind.UnmanagedNullable
                or MemberKind.Blank);
        var callbackCount = new[]
        {
            OnSerializing,
            OnSerialized,
            OnDeserialized,
            OnDeserializing,
        }.Select(x => x.Length).Sum();
        if (fixedSize &&
            GenerateType == GenerateType.Object &&
            !IsValueType &&
            callbackCount == 0)
        {
            var sizeOf = string.Join(
                " + ",
                Members.Select(x =>
                    $"System.Runtime.CompilerServices.Unsafe.SizeOf<{x.MemberType.FullyQualifiedToString()}>()"));
            var headerPlus = Members.Length == 0 ? "1" : "1 + ";
            fixedSizeInterface = ", global::SharpPack.IFixedSizeSharpPackable";
            fixedSizeMethod = $$"""

    [global::SharpPack.Internal.Preserve]
    static int global::SharpPack.IFixedSizeSharpPackable.Size => {{headerPlus}}{{sizeOf}};

""";
        }

        var exactSizeEligible =
            !IsValueType &&
            !fixedSize &&
            GenerateType == GenerateType.Object &&
            callbackCount == 0 &&
            Members.All(static member => member.HasExactSizeSafeAccessor &&
                member.Kind is
                MemberKind.Unmanaged or
                MemberKind.Enum or
                MemberKind.UnmanagedNullable or
                MemberKind.String or
                MemberKind.UnmanagedArray);
        if (exactSizeEligible)
        {
            exactSizeInterface =
                $", global::SharpPack.ISharpPackExactSizeSerializable<{TypeName}>";
            exactSizeMethod = EmitExactSizeSerializeMethod();
        }
        const string serializeMethodSignarture =
            "Serialize<TBufferWriter>(ref SharpPackWriter<TBufferWriter>";

        foreach (var container in containingTypes)
        {
            writer.AppendLine(EmitPartialTypeDeclaration(container));
            writer.AppendLine(EmitTypeParameterConstraints(
                container.TypeParameters));
            writer.AppendLine("{");
        }

        var contextFactoryInterface =
            $", global::SharpPack.ISharpPackFormatterFactory<{TypeName}>" +
            $", global::SharpPack.ISharpPackContextFormatterFactory<{TypeName}>";
        var contextDependencyCondition = IsUnmanagedType
            ? ""
            : EmitFormatterOverrideDependencyCondition(
                "context",
                useOptionalState: false);
        var contextFormatterSelection =
            contextDependencyCondition.Length == 0
                ? $"return new global::SharpPack.Formatters.SharpPackableFormatter<{TypeName}>();"
                : $$"""
        if ({{contextDependencyCondition}})
        {
            return new {{contextFormatterTypeName}}();
        }
        return new global::SharpPack.Formatters.SharpPackableFormatter<{{TypeName}}>();
""";
        var aotFormatterRoots = EmitAotFormatterRoots("        ");
        var aotRootMethodName = "__SharpPackEnsureAotFormatterRoots";
        while (Symbol.GetAllMembers().Any(
                   member => member.Name == aotRootMethodName) ||
               Symbol.TypeParameters.Any(
                   parameter => parameter.Name == aotRootMethodName))
        {
            aotRootMethodName += "_";
        }
        var aotRootCall = aotFormatterRoots.Length == 0
            ? ""
            : $"        {aotRootMethodName}();";
        var aotRootMethod = aotFormatterRoots.Length == 0
            ? ""
            : $$"""

    [global::SharpPack.Internal.Preserve]
    static void {{aotRootMethodName}}()
    {
{{aotFormatterRoots}}
    }
""";
        var contextFactoryMethod = $$"""

    [global::SharpPack.Internal.Preserve]
    static global::SharpPack.SharpPackFormatter<{{TypeName}}> global::SharpPack.ISharpPackFormatterFactory<{{TypeName}}>.CreateFormatter()
    {
{{aotRootCall}}
        return new global::SharpPack.Formatters.SharpPackableFormatter<{{TypeName}}>();
    }

    [global::SharpPack.Internal.Preserve]
    static global::SharpPack.SharpPackFormatter<{{TypeName}}> global::SharpPack.ISharpPackContextFormatterFactory<{{TypeName}}>.CreateFormatter(
        global::SharpPack.SharpPackSerializerContext context)
    {
{{aotRootCall}}
        {{contextFormatterSelection}}
    }
{{aotRootMethod}}
""";

        writer.AppendLine($$"""
partial {{classOrStructOrRecord}} {{TypeName}} : ISharpPackable<{{TypeName}}>{{fixedSizeInterface}}{{exactSizeInterface}}{{contextFactoryInterface}}
{
{{(IsUnmanagedType ? "" : EmitCustomFormatters())}}
    static partial void StaticConstructor();

    static {{Symbol.Name}}()
    {
        StaticConstructor();
    }
{{fixedSizeMethod}}
{{exactSizeMethod}}
{{contextFactoryMethod}}
{{formatterOverrideMethods}}

    [global::SharpPack.Internal.Preserve]
    {{staticSharpPackableMethod}}{{serializeMethodSignarture}} writer, {{scopedRef}} {{TypeName}}{{nullable}} value) {{constraint}}
    {
{{(IsUnmanagedType ? "" : OnSerializing.Select(x => "        " + x.Emit()).NewLine())}}
{{serializeBody}}
    END:
{{(IsUnmanagedType ? "" : OnSerialized.Select(x => "        " + x.Emit()).NewLine())}}
        return;
    }

    [global::SharpPack.Internal.Preserve]
    {{staticSharpPackableMethod}}Deserialize(ref SharpPackReader reader, {{scopedRef}} {{TypeName}}{{nullable}} value)
    {
{{(IsUnmanagedType ? "" : OnDeserializing.Select(x => "        " + x.Emit()).NewLine())}}
{{deserializeBody}}
    END:
{{(IsUnmanagedType ? "" : OnDeserialized.Select(x => "        " + x.Emit()).NewLine())}}
        return;
    }

}
""");

        for(int i = 0; i < containingTypes.Count; ++i)
        {
            writer.AppendLine("}");
        }
    }

    private string EmitDeserializeBody()
    {
        return EmitDeserializeBodyCore(
            honorFormatterOverrides: false);
    }

    private string EmitDeserializeBodyCore(bool honorFormatterOverrides)
    {
        var count = Members.Length;

        var isVersionTolerant = this.GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference;
        var readBeginBody = "";
        var readEndBody = "";
        var commentOutInvalidBody = "";
        var circularReferenceBody = "";
        var circularReferenceBody2 = "";

        if (isVersionTolerant)
        {
            readBeginBody = """
        Span<int> deltas = stackalloc int[count];
        long totalDelta = 0;
        for (int i = 0; i < count; i++)
        {
            deltas[i] = reader.ReadVarIntInt32();
            if (deltas[i] < 0)
            {
                SharpPackSerializationException.ThrowInvalidLength(deltas[i]);
            }
            totalDelta += deltas[i];
        }
        if (totalDelta > reader.Remaining)
        {
            SharpPackSerializationException.ThrowInvalidAdvance();
        }
""";

            readEndBody = """
        if (count == readCount) goto END;

        for (int i = readCount; i < count; i++)
        {
            reader.Advance(deltas[i]);
        }
""";

            commentOutInvalidBody = "// ";
        }
        if (GenerateType == GenerateType.CircularReference)
        {
            circularReferenceBody = $$"""
        uint id;
        if (count == SharpPackCode.ReferenceId)
        {
            id = reader.ReadVarIntUInt32();
            value = ({{TypeName}})reader.OptionalState.GetObjectReference(id);
            goto END;
        }
""";

            circularReferenceBody2 = $$"""
        id = reader.ReadVarIntUInt32();
        if (value == null)
        {
            value = new {{TypeName}}();
        }
        reader.OptionalState.AddObjectReference(id, value);
""";
        }

        return $$"""
        if (!reader.TryReadObjectHeader(out var count))
        {
            value = default!;
            goto END;
        }
{{circularReferenceBody}}
{{readBeginBody}}
{{circularReferenceBody2}}
{{Members.Where(x => x.Symbol != null).Select(x => $"        {x.MemberType.FullyQualifiedToString()} __{x.Name};").NewLine()}}

        {{(!isVersionTolerant ? "" : "var readCount = " + count + ";")}}
        if (count == {{count}})
        {
            {{(IsValueType ? "" : "if (value == null)")}}
            {
{{EmitDeserializeMembers(
    Members,
    "                ",
    honorFormatterOverrides)}}

                goto NEW;
            }
{{(IsValueType ? "#if false" : "            else")}}
            {
{{Members.Where(x => x.Symbol != null).Select(x => $"                __{x.Name} = value.@{x.Name};").NewLine()}}

{{EmitReadRefDeserializeMembers(
    Members,
    "                ",
    includeCountJumps: false,
    honorFormatterOverrides)}}

                goto SET;
            }
{{(IsValueType ? "#endif" : "")}}
        }
        {{commentOutInvalidBody}}else if (count > {{count}})
        {{commentOutInvalidBody}}{
            {{commentOutInvalidBody}}SharpPackSerializationException.ThrowInvalidPropertyCount(typeof({{TypeName}}), {{count}}, count);
            {{commentOutInvalidBody}}goto READ_END;
        {{commentOutInvalidBody}}}
        else
        {
            {{(IsValueType ? "" : "if (value == null)")}}
            {
{{Members.Where(x => x.Symbol != null).Select(x => $"               __{x.Name} = default!;").NewLine()}}
            }
{{(IsValueType ? "#if false" : "            else")}}
            {
{{Members.Where(x => x.Symbol != null).Select(x => $"               __{x.Name} = value.@{x.Name};").NewLine()}}
            }
{{(IsValueType ? "#endif" : "")}}

            if (count == 0) goto SKIP_READ;
{{EmitReadRefDeserializeMembers(
    Members,
    "            ",
    includeCountJumps: true,
    honorFormatterOverrides)}}

    SKIP_READ:
            {{(IsValueType ? "" : "if (value == null)")}}
            {
                goto NEW;
            }
{{(IsValueType ? "#if false" : "            else")}}
            {
                goto SET;
            }
{{(IsValueType ? "#endif" : "")}}
        }

    SET:
        {{(!IsUseEmptyConstructor ? "goto NEW;" : "")}}
{{Members.Where(x => x.IsAssignable).Select(x => $"        {(IsUseEmptyConstructor ? "" : "// ")}value.@{x.Name} = __{x.Name};").NewLine()}}
        goto READ_END;

    NEW:
        value = {{EmitConstructor()}}
        {
{{EmitDeserializeConstruction("            ")}}
        };
{{EmitDeserializeConstructionWithBranching("        ")}}
    READ_END:
{{readEndBody}}
""";
    }

    string EmitCustomFormatters()
    {
        var sb = new StringBuilder();
        foreach (var item in Members.Where(x => x.Kind == MemberKind.CustomFormatter))
        {
            var attribute = item.CustomFormatterAttribute!;
            var arguments = string.Join(
                ", ",
                attribute.ConstructorArguments.Select(EmitTypedConstant));
            var initializers = attribute.NamedArguments
                .Select(static pair =>
                    $"@{pair.Key} = {EmitTypedConstant(pair.Value)}")
                .ToArray();
            var initializer = initializers.Length == 0
                ? ""
                : $" {{ {string.Join(", ", initializers)} }}";

            sb.AppendLine(
                $"    static readonly {item.CustomFormatterName} __{item.Name}Formatter = " +
                $"new {item.CustomFormatter!.FullyQualifiedToString()}({arguments})" +
                $"{initializer}.GetFormatter();");
        }
        return sb.ToString();
    }

    static string EmitTypedConstant(TypedConstant constant)
    {
        if (constant.IsNull)
        {
            return "null";
        }

        return constant.Kind switch
        {
            TypedConstantKind.Primitive =>
                Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatPrimitive(
                    constant.Value!,
                    quoteStrings: true,
                    useHexadecimalNumbers: false),
            TypedConstantKind.Enum =>
                $"({constant.Type!.FullyQualifiedToString()})" +
                Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatPrimitive(
                    constant.Value!,
                    quoteStrings: false,
                    useHexadecimalNumbers: false),
            TypedConstantKind.Type =>
                $"typeof({((ITypeSymbol)constant.Value!).FullyQualifiedToString()})",
            TypedConstantKind.Array =>
                $"new {((IArrayTypeSymbol)constant.Type!).ElementType.FullyQualifiedToString()}[]" +
                $" {{ {string.Join(", ", constant.Values.Select(EmitTypedConstant))} }}",
            _ => throw new InvalidOperationException(
                $"Unsupported custom formatter attribute argument: {constant.Kind}."),
        };
    }

    string EmitAotFormatterRoots(string indent)
    {
        var formatterTypes = new HashSet<string>(StringComparer.Ordinal);
        var factoryTypes = new HashSet<string>(StringComparer.Ordinal);

        foreach (var member in Members)
        {
            AddFormatterTypes(member.MemberType);
        }

        if (formatterTypes.Count == 0 && factoryTypes.Count == 0)
        {
            return "";
        }

        var sb = new StringBuilder();
        sb.AppendLine(
            $"{indent}if (!global::System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported)");
        sb.AppendLine($"{indent}{{");
        foreach (var formatterType in formatterTypes.OrderBy(static x => x))
        {
            sb.AppendLine(
                $"{indent}    global::System.GC.KeepAlive(new {formatterType}());");
        }
        foreach (var factoryType in factoryTypes.OrderBy(static x => x))
        {
            sb.AppendLine(
                $"{indent}    global::System.GC.KeepAlive(PreserveFactory<{factoryType}, {factoryType}>());");
            sb.AppendLine(
                $"{indent}    global::System.GC.KeepAlive(typeof({factoryType}).GetMethods(global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic));");
        }
        if (factoryTypes.Count != 0)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"{indent}    static global::System.Func<global::SharpPack.SharpPackFormatter<TValue>> PreserveFactory<TValue, TFactory>()");
            sb.AppendLine(
                $"{indent}        where TFactory : global::SharpPack.ISharpPackFormatterFactory<TValue>");
            sb.AppendLine(
                $"{indent}        => TFactory.CreateFormatter;");
        }
        sb.Append($"{indent}}}");
        return sb.ToString();

        void AddFormatterTypes(ITypeSymbol type)
        {
            if (reference.KnownTypes.GetNonDefaultFormatterName(type) is { } formatter)
            {
                formatterTypes.Add(formatter);
            }

            if (type.TryGetSharpPackableType(
                    reference,
                    out var generateType,
                    out _) &&
                generateType != GenerateType.NoGenerate)
            {
                factoryTypes.Add(type.FullyQualifiedToString());
            }

            if (type is IArrayTypeSymbol array)
            {
                AddFormatterTypes(array.ElementType);
            }
            else if (type is INamedTypeSymbol named)
            {
                foreach (var argument in named.TypeArguments)
                {
                    AddFormatterTypes(argument);
                }
            }
        }
    }

    string EmitSerializeBody()
    {
        if (this.GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference)
        {
            return Members.All(x =>
                x.Kind is MemberKind.Unmanaged
                    or MemberKind.String
                    or MemberKind.Enum
                    or MemberKind.UnmanagedArray
                    or MemberKind.UnmanagedNullable
                    or MemberKind.Blank)
                ? EmitVersionTorelantSerializeBodyOptimized()
                : EmitVersionTorelantSerializeBody(
                    honorFormatterOverrides: false);
        }

        return EmitObjectSerializeBody(honorFormatterOverrides: false);
    }

    string EmitExactSizeSerializeMethod()
    {
        var captureMembers = Members
            .Select((member, index) => member.Kind == MemberKind.String
                ? $"""
        var __value{index} = this.@{member.Name};
        var __utf8Length{index} = __value{index} is null || __value{index}.Length == 0
            ? 0
            : global::System.Text.Encoding.UTF8.GetByteCount(__value{index});
"""
                : $"        var __value{index} = this.@{member.Name};")
            .NewLine();
        var sizeTerms = Members
            .Select((member, index) => member.Kind switch
            {
                MemberKind.Unmanaged or
                MemberKind.Enum or
                MemberKind.UnmanagedNullable =>
                    $"global::System.Runtime.CompilerServices.Unsafe.SizeOf<{member.MemberType.FullyQualifiedToString()}>()",
                MemberKind.String =>
                    $"(__value{index} is null || __value{index}.Length == 0 ? 4L : (long)__utf8Length{index} + 8)",
                MemberKind.UnmanagedArray =>
                    $"(__value{index} is null || __value{index}.Length == 0 ? 4L : (long)__value{index}.Length * global::System.Runtime.CompilerServices.Unsafe.SizeOf<{((IArrayTypeSymbol)member.MemberType).ElementType.FullyQualifiedToString()}>() + 4)",
                _ => throw new InvalidOperationException(),
            });
        var writeMembers = Members
            .Select((member, index) => member.Kind switch
            {
                MemberKind.Unmanaged or MemberKind.Enum =>
                    $"        writer.WriteUnmanaged(__value{index});",
                MemberKind.UnmanagedNullable =>
                    $"        writer.DangerousWriteUnmanaged(__value{index});",
                MemberKind.String =>
                    $"        writer.WriteUtf8Exact(__value{index}, __utf8Length{index});",
                MemberKind.UnmanagedArray =>
                    $"        writer.WriteUnmanagedArray(__value{index});",
                _ => throw new InvalidOperationException(),
            })
            .NewLine();
        var sizeExpression = string.Join(
            " + " + Environment.NewLine + "            ",
            sizeTerms);

        return $$"""

    [global::SharpPack.Internal.Preserve]
    byte[] global::SharpPack.ISharpPackExactSizeSerializable<{{TypeName}}>.SerializeExact()
    {
{{captureMembers}}
        var size = 1L +
            {{sizeExpression}};
        if ((ulong)size > (ulong)global::System.Array.MaxLength)
        {
            global::SharpPack.SharpPackSerializationException.ThrowSizeOverflow();
        }
        var buffer = global::System.GC.AllocateUninitializedArray<byte>((int)size);
        var bufferWriter =
            new global::SharpPack.Internal.SharpPackExactArrayBufferWriter(buffer);
        var writer = global::SharpPack.SharpPackSerializer.CreateExactWriter(
            ref bufferWriter);
        writer.WriteObjectHeader({{Members.Length}});
{{writeMembers}}
        writer.Flush();
        return bufferWriter.GetFilledBuffer();
    }
""";
    }

    string EmitFormatterOverrideMethods(string contextFormatterTypeName)
    {
        var writerCondition =
            EmitFormatterOverrideDependencyCondition("writer");
        if (writerCondition.Length == 0)
        {
            return "";
        }

        var overrideSerializeBody =
            GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference
                ? EmitVersionTorelantSerializeBody(
                    honorFormatterOverrides: true)
                : EmitObjectSerializeBody(
                    honorFormatterOverrides: true);
        var overrideDeserializeBody = EmitDeserializeBodyCore(
            honorFormatterOverrides: true);
        var nullable = IsValueType ? "" : "?";
        var serializeHelperName =
            GetFormatterOverrideHelperName(serialize: true);
        var deserializeHelperName =
            GetFormatterOverrideHelperName(serialize: false);

        return $$"""

    [global::System.Runtime.CompilerServices.MethodImpl(
        global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    static void {{serializeHelperName}}<TBufferWriter>(
        ref global::SharpPack.SharpPackWriter<TBufferWriter> writer,
        scoped ref {{TypeName}}{{nullable}} value)
        where TBufferWriter : global::System.Buffers.IBufferWriter<byte>
    {
{{OnSerializing.Select(x => "        " + x.Emit()).NewLine()}}
{{overrideSerializeBody}}
    END:
{{OnSerialized.Select(x => "        " + x.Emit()).NewLine()}}
        return;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(
        global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    static void {{deserializeHelperName}}(
        ref global::SharpPack.SharpPackReader reader,
        scoped ref {{TypeName}}{{nullable}} value)
    {
{{OnDeserializing.Select(x => "        " + x.Emit()).NewLine()}}
{{overrideDeserializeBody}}
    END:
{{OnDeserialized.Select(x => "        " + x.Emit()).NewLine()}}
        return;
    }

    [global::SharpPack.Internal.Preserve]
    sealed class {{contextFormatterTypeName}}
        : global::SharpPack.SharpPackFormatter<{{TypeName}}>,
          global::SharpPack.ISharpPackContextOverrideFormatter
    {
        public override void Serialize<TBufferWriter>(
            ref global::SharpPack.SharpPackWriter<TBufferWriter> writer,
            scoped ref {{TypeName}}{{nullable}} value)
            => {{serializeHelperName}}(ref writer, ref value);

        public override void Deserialize(
            ref global::SharpPack.SharpPackReader reader,
            scoped ref {{TypeName}}{{nullable}} value)
            => {{deserializeHelperName}}(ref reader, ref value);
    }
""";
    }

    string GetFormatterOverrideHelperName(bool serialize)
    {
        var name = serialize
            ? "__SharpPackSerializeWithFormatterOverrides"
            : "__SharpPackDeserializeWithFormatterOverrides";
        while (Symbol.GetAllMembers().Any(member => member.Name == name) ||
               Symbol.TypeParameters.Any(parameter => parameter.Name == name))
        {
            name += "_";
        }
        return name;
    }

    string EmitObjectSerializeBody(bool honorFormatterOverrides)
    {
        return $$"""
{{(!IsValueType ? $$"""
        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }
""" : "")}}

{{EmitSerializeMembers(
    Members,
    "        ",
    toTempWriter: false,
    writeObjectHeader: true,
    honorFormatterOverrides)}}
""";
    }

    string EmitVersionTorelantSerializeBody(bool honorFormatterOverrides)
    {
        const string newTempWriter =
            "new SharpPackWriter<global::SharpPack.Internal.ReusableLinkedArrayBufferWriter>(ref tempBuffer, writer.OptionalState)";

        var checkCircularReference = "";
        if (GenerateType == GenerateType.CircularReference)
        {
            checkCircularReference = """
        var (existsReference, id) = writer.OptionalState.GetOrAddReference(value);
        if (existsReference)
        {
            writer.WriteObjectReferenceId(id);
            goto END;
        }
""";
        }

        return $$"""
{{(!IsValueType ? $$"""
        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }
""" : "")}}
{{checkCircularReference}}
        var tempBuffer = global::SharpPack.Internal.ReusableLinkedArrayBufferWriterPool.Rent(
            out var tempBufferLeaseId);
        try
        {
            Span<int> offsets = stackalloc int[{{Members.Length}}];
            var tempWriter = {{newTempWriter}};

{{EmitSerializeMembers(
    Members,
    "            ",
    toTempWriter: true,
    writeObjectHeader: false,
    honorFormatterOverrides)}}

            tempWriter.Flush();

            writer.WriteObjectHeader({{Members.Length}});
            for (int i = 0; i < {{Members.Length}}; i++)
            {
                int delta;
                if (i == 0)
                {
                    delta = offsets[i];
                }
                else
                {
                    delta = offsets[i] - offsets[i - 1];
                }
                writer.WriteVarInt(delta);
            }
            {{(GenerateType == GenerateType.CircularReference ? "writer.WriteVarInt(id);" : "")}}
            tempBuffer.WriteToAndReset(ref writer);
        }
        finally
        {
            global::SharpPack.Internal.ReusableLinkedArrayBufferWriterPool.Return(
                tempBuffer,
                tempBufferLeaseId);
        }
""";
    }

    // Optimized is all member is fixed size
    string EmitVersionTorelantSerializeBodyOptimized()
    {
        static string EmitLengthHeader(MemberMeta[] members)
        {
            var sb = new StringBuilder();
            foreach (var item in members)
            {
                sb.AppendLine("        " + item.EmitVarIntLength());
            }
            return sb.ToString();
        }

        var checkCircularReference = "";
        if (GenerateType == GenerateType.CircularReference)
        {
            checkCircularReference = """
        var (existsReference, id) = writer.OptionalState.GetOrAddReference(value);
        if (existsReference)
        {
            writer.WriteObjectReferenceId(id);
            goto END;
        }
""";
        }

        return $$"""
{{(!IsValueType ? $$"""
        if (value == null)
        {
            writer.WriteNullObjectHeader();
            goto END;
        }
""" : "")}}
{{checkCircularReference}}
        writer.WriteObjectHeader({{Members.Length}});
{{EmitLengthHeader(Members)}}
        {{(GenerateType == GenerateType.CircularReference ? "writer.WriteVarInt(id);" : "")}}
{{EmitSerializeMembers(Members, "        ", toTempWriter: false, writeObjectHeader: false)}}
""";
    }

    // toTempWriter is VersionTolerant
    public string EmitSerializeMembers(
        MemberMeta[] members,
        string indent,
        bool toTempWriter,
        bool writeObjectHeader,
        bool honorFormatterOverrides = false)
    {
        // members is guranteed writable.
        if (members.Length == 0 && writeObjectHeader)
        {
            return $"{indent}writer.WriteObjectHeader(0);";
        }

        var writer = toTempWriter ? "tempWriter" : "writer";

        var sb = new StringBuilder();
        for (int i = 0; i < members.Length; i++)
        {
            if (honorFormatterOverrides ||
                !(members[i].Kind is MemberKind.Unmanaged or MemberKind.Enum or MemberKind.UnmanagedNullable) ||
                toTempWriter)
            {
                sb.Append(indent);
                if (i == 0 && writeObjectHeader)
                {
                    sb.AppendLine($"{writer}.WriteObjectHeader({Members.Length});");
                    sb.Append(indent);
                }

                sb.Append(members[i].EmitSerialize(
                    writer,
                    honorFormatterOverrides));
                if (toTempWriter)
                {
                    sb.AppendLine($" offsets[{i}] = tempWriter.WrittenCount;");
                }
                else
                {
                    sb.AppendLine();
                }
                continue;
            }

            // search optimization
            var optimizeFrom = i;
            var optimizeTo = i;
            var limit = Math.Min(members.Length, i + 15);
            var dangerous = "";
            for (int j = i; j < limit; j++)
            {
                if (members[j].Kind is MemberKind.Unmanaged or MemberKind.Enum or MemberKind.UnmanagedNullable)
                {
                    if (members[j].Kind is MemberKind.UnmanagedNullable)
                    {
                        dangerous = "Dangerous";
                    }
                    optimizeTo = j;
                    continue;
                }
                else
                {
                    break;
                }
            }

            // write method
            sb.Append(indent);
            if (optimizeFrom == 0 && writeObjectHeader)
            {
                sb.Append($"{writer}.{dangerous}WriteUnmanagedWithObjectHeader(");
                sb.Append(members.Length);
                sb.Append(", ");
            }
            else
            {
                sb.Append($"{writer}.{dangerous}WriteUnmanaged(");
            }

            for (int index = optimizeFrom; index <= optimizeTo; index++)
            {
                if (index != i)
                {
                    sb.Append(", ");
                }
                sb.Append("value.@");
                sb.Append(members[index].Name);
            }
            sb.Append(");");

            if (toTempWriter)
            {
                sb.AppendLine($" offsets[{i}] = tempWriter.WrittenCount;");
            }
            else
            {
                sb.AppendLine();
            }

            i = optimizeTo;
        }

        return sb.ToString();
    }

    // for optimize, can use same count, value == null.
    public string EmitDeserializeMembers(
        MemberMeta[] members,
        string indent,
        bool honorFormatterOverrides)
    {
        return EmitDeserializeMembersCore(
            members,
            indent,
            honorFormatterOverrides);
    }

    string EmitDeserializeMembersCore(
        MemberMeta[] members,
        string indent,
        bool honorFormatterOverrides)
    {
        // {{Members.Select(x => "                " + x.EmitReadToDeserialize()).NewLine()}}
        var sb = new StringBuilder();
        for (int i = 0; i < members.Length; i++)
        {
            if (honorFormatterOverrides ||
                !(members[i].Kind is MemberKind.Unmanaged or MemberKind.Enum or MemberKind.UnmanagedNullable) ||
                (GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference))
            {
                sb.Append(indent);
                sb.AppendLine(members[i].EmitReadToDeserialize(
                    i,
                    GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference,
                    honorFormatterOverrides));
                continue;
            }

            // search optimization
            var optimizeFrom = i;
            var optimizeTo = i;
            var limit = Math.Min(members.Length, i + 15);
            var dangerous = "";
            for (int j = i; j < limit; j++)
            {
                if (members[j].Kind is MemberKind.Unmanaged or MemberKind.Enum or MemberKind.UnmanagedNullable)
                {
                    if (members[j].Kind is MemberKind.UnmanagedNullable)
                    {
                        dangerous = "Dangerous";
                    }
                    optimizeTo = j;
                    continue;
                }
                else
                {
                    break;
                }
            }

            // write read method
            sb.Append(indent);
            sb.Append($"reader.{dangerous}ReadUnmanaged(");

            for (int index = optimizeFrom; index <= optimizeTo; index++)
            {
                if (index != i)
                {
                    sb.Append(", ");
                }
                sb.Append("out __");
                sb.Append(members[index].Name);
            }
            sb.AppendLine(");");

            i = optimizeTo;
        }

        return sb.ToString();
    }

    string EmitFormatterOverrideDependencyCondition(
        string receiver,
        bool useOptionalState = true)
    {
        var types = new List<ITypeSymbol>();
        foreach (var member in Members)
        {
            if (member.Kind is MemberKind.Blank or MemberKind.CustomFormatter)
            {
                continue;
            }
            AddTypeAndDependencies(member.MemberType);
        }

        var registrations = types
            .Select(static type =>
                type.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat))
            .Distinct(StringComparer.Ordinal)
            .Select(type => useOptionalState
                ? $"{receiver}.OptionalState.HasFormatterOverride<{type}>()"
                : $"{receiver}.HasFormatterOverrideDependency<{type}>()");
        var registrationCondition = string.Join(" || ", registrations);
        return registrationCondition;

        void AddTypeAndDependencies(ITypeSymbol type)
        {
            types.Add(type);
            if (type is IArrayTypeSymbol array)
            {
                AddTypeAndDependencies(array.ElementType);
                return;
            }

            if (type is not INamedTypeSymbol named ||
                !named.IsGenericType ||
                !reference.KnownTypes.Contains(named))
            {
                return;
            }

            foreach (var argument in named.TypeArguments)
            {
                AddTypeAndDependencies(argument);
            }
        }
    }

    string EmitReadRefDeserializeMembers(
        MemberMeta[] members,
        string indent,
        bool includeCountJumps,
        bool honorFormatterOverrides)
    {
        return members
            .Select((member, index) =>
                indent +
                member.EmitReadRefDeserialize(
                    member.Order,
                    GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference,
                    honorFormatterOverrides) +
                (includeCountJumps
                    ? $" if (count == {index + 1}) goto SKIP_READ;"
                    : ""))
            .NewLine();
    }

    string EmitConstructor()
    {
        // no need `;` because after using object initializer
        if (this.Constructor == null || this.Constructor.Parameters.Length == 0)
        {
            return $"new {TypeName}()";
        }
        else
        {
            var nameDict = Members.Where(x => x.IsConstructorParameter).ToDictionary(x => x.ConstructorParameterName, x => x.Name, StringComparer.OrdinalIgnoreCase);
            var parameters = this.Constructor.Parameters
                .Select(x =>
                {
                    if (nameDict.TryGetValue(x.Name, out var name))
                    {
                        return $"__{name}";
                    }
                    return null; // invalid, validated.
                })
                .Where(x => x != null);

            return $"new {TypeName}({string.Join(", ", parameters)})";
        }
    }

    string EmitDeserializeConstruction(string indent)
    {
        // all value is deserialized, __Name is exsits.
        return string.Join("," + Environment.NewLine, Members
            .Where(x => x is { IsSettable: true, IsConstructorParameter: false, SuppressDefaultInitialization: false })
            .Select(x => $"{indent}@{x.Name} = __{x.Name}"));
    }

    string EmitDeserializeConstructionWithBranching(string indent)
    {
        var members = Members
            .Select((x, i) => (x, i))
            .Where(v => v.x.SuppressDefaultInitialization);

        var lines = GenerateType is GenerateType.VersionTolerant or GenerateType.CircularReference
            ? members.Select(v => $"{indent}if (deltas.Length > {v.i} && deltas[{v.i}] != 0) value.@{v.x.Name} = __{v.x.Name};")
            : members.Select(v => $"{indent}if ({v.i + 1} <= count) value.@{v.x.Name} = __{v.x.Name};");

        return lines.NewLine();
    }

    string EmitUnionTemplate(IGeneratorContext context)
    {
        var classOrInterfaceOrRecord = IsRecord ? "record" : (Symbol.TypeKind == TypeKind.Interface) ? "interface" : "class";

        var contextFactoryInterface =
            $"global::SharpPack.ISharpPackFormatterFactory<{TypeName}>";
        var contextFactoryMethod = $$"""

    [global::SharpPack.Internal.Preserve]
    static global::SharpPack.SharpPackFormatter<{{TypeName}}> global::SharpPack.ISharpPackFormatterFactory<{{TypeName}}>.CreateFormatter()
    {
        return new {{Symbol.Name}}Formatter();
    }
""";
        const string scopedRef = "scoped ref";
        const string serializeMethodSignarture =
            "Serialize<TBufferWriter>(ref SharpPackWriter<TBufferWriter>";

        var code = $$"""

partial {{classOrInterfaceOrRecord}} {{TypeName}} : {{contextFactoryInterface}}
{
    static partial void StaticConstructor();

    static {{Symbol.Name}}()
    {
        StaticConstructor();
    }
{{contextFactoryMethod}}

    [global::SharpPack.Internal.Preserve]
    sealed class {{Symbol.Name}}Formatter : SharpPackFormatter<{{TypeName}}>
    {
{{EmitUnionTypeToTagField()}}

        [global::SharpPack.Internal.Preserve]
        public override void {{serializeMethodSignarture}} writer, {{scopedRef}} {{TypeName}}? value)
        {
{{OnSerializing.Select(x => "            " + x.Emit()).NewLine()}}
{{EmitUnionSerializeBody()}}
{{OnSerialized.Select(x => "            " + x.Emit()).NewLine()}}
        }

        [global::SharpPack.Internal.Preserve]
        public override void Deserialize(ref SharpPackReader reader, {{scopedRef}} {{TypeName}}? value)
        {
{{OnDeserializing.Select(x => "            " + x.Emit()).NewLine()}}
{{EmitUnionDeserializeBody()}}
{{OnDeserialized.Select(x => "            " + x.Emit()).NewLine()}}
        }
    }
}
""";

        return code;
    }

    public void EmitUnionFormatterTemplate(StringBuilder writer, IGeneratorContext context, INamedTypeSymbol formatterSymbol)
    {
        const string scopedRef = "scoped ref";
        const string serializeMethodSignarture =
            "Serialize<TBufferWriter>(ref SharpPackWriter<TBufferWriter>";

        var symbolFullQualified = ToUnionTagTypeFullyQualifiedToString(Symbol);
        var formatterTypeParameters = formatterSymbol.TypeParameters.Length == 0
            ? ""
            : $"<{string.Join(", ", formatterSymbol.TypeParameters.Select(static parameter => parameter.Name))}>";
        var registrationConstraints = EmitTypeParameterConstraints(
            formatterSymbol.TypeParameters);
        var registrationClassName =
            $"{formatterSymbol.Name}SharpPackContextExtensions";
        var registrationMethodName =
            $"Register{formatterSymbol.Name}";

        var code = $$"""
[global::SharpPack.Internal.Preserve]
partial class {{TypeName}} :
    SharpPackFormatter<{{symbolFullQualified}}>,
    global::SharpPack.ISharpPackFormatterFactory<{{symbolFullQualified}}>
{{registrationConstraints}}
{
    static global::SharpPack.SharpPackFormatter<{{symbolFullQualified}}>
        global::SharpPack.ISharpPackFormatterFactory<{{symbolFullQualified}}>.CreateFormatter()
    {
        return new {{TypeName}}();
    }

{{EmitUnionTypeToTagField()}}

        [global::SharpPack.Internal.Preserve]
        public override void {{serializeMethodSignarture}} writer, {{scopedRef}} {{symbolFullQualified}}? value)
        {
{{OnSerializing.Select(x => "            " + x.Emit()).NewLine()}}
{{EmitUnionSerializeBody()}}
{{OnSerialized.Select(x => "            " + x.Emit()).NewLine()}}
        }

        [global::SharpPack.Internal.Preserve]
        public override void Deserialize(ref SharpPackReader reader, {{scopedRef}} {{symbolFullQualified}}? value)
        {
{{OnDeserializing.Select(x => "            " + x.Emit()).NewLine()}}
{{EmitUnionDeserializeBody()}}
{{OnDeserialized.Select(x => "            " + x.Emit()).NewLine()}}
        }
}

[global::SharpPack.Internal.Preserve]
public static class {{registrationClassName}}
{
    public static global::SharpPack.SharpPackSerializerContextBuilder
        {{registrationMethodName}}{{formatterTypeParameters}}(
            this global::SharpPack.SharpPackSerializerContextBuilder builder)
{{registrationConstraints}}
    {
        global::System.ArgumentNullException.ThrowIfNull(builder);
        return builder.RegisterFactory<
            {{symbolFullQualified}},
            {{TypeName}}>();
    }
}
""";

        writer.AppendLine(code);
    }

    internal static string EmitPartialTypeDeclaration(INamedTypeSymbol symbol)
    {
        var kind = (symbol.TypeKind, symbol.IsRecord, symbol.IsValueType) switch
        {
            (TypeKind.Interface, _, _) => "interface",
            (_, true, true) => "record struct",
            (_, true, false) => "record",
            (_, false, true) => "struct",
            _ => "class",
        };
        var typeParameters = symbol.TypeParameters.Length == 0
            ? ""
            : $"<{string.Join(", ", symbol.TypeParameters.Select(
                static parameter => parameter.Name))}>";
        return $"partial {kind} {symbol.Name}{typeParameters}";
    }

    internal static string EmitTypeParameterConstraints(
        ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        var clauses = new List<string>();
        foreach (var parameter in typeParameters)
        {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }
            else if (parameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }
            else if (parameter.HasReferenceTypeConstraint)
            {
                constraints.Add(
                    parameter.ReferenceTypeConstraintNullableAnnotation ==
                    NullableAnnotation.Annotated
                        ? "class?"
                        : "class");
            }
            else if (parameter.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            constraints.AddRange(parameter.ConstraintTypes.Select(
                static constraint => constraint.FullyQualifiedToString()));

            if (parameter.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count != 0)
            {
                clauses.Add(
                    $"        where {parameter.Name} : {string.Join(", ", constraints)}");
            }
        }

        return clauses.Count == 0
            ? ""
            : string.Join(Environment.NewLine, clauses);
    }

    string ToUnionTagTypeFullyQualifiedToString(INamedTypeSymbol type)
    {
        if (type.IsGenericType && this.Symbol.IsGenericType)
        {
            // when generic type, it is unconstructed.( typeof(T<>) ) so construct symbol's T
            var typeName = string.Join(", ", this.Symbol.TypeArguments.Select(x => x.FullyQualifiedToString()));
            return type.FullyQualifiedToString().Replace("<>", "<" + typeName + ">");
        }
        else
        {
            return type.FullyQualifiedToString();
        }
    }

    string EmitUnionTypeToTagField()
    {
        var elements = UnionTags.Select(x => $"            {{ typeof({ToUnionTagTypeFullyQualifiedToString(x.Type)}), {x.Tag} }},").NewLine();

        return $$"""
        static readonly System.Collections.Generic.Dictionary<Type, ushort> __typeToTag = new({{UnionTags.Length}})
        {
{{elements}}
        };
""";
    }

    string EmitUnionSerializeBody()
    {
        var symbolFullQualified = ToUnionTagTypeFullyQualifiedToString(Symbol);

        var writeBody = UnionTags
            .Select(x =>
            {
                var method = (x.Type.TryGetSharpPackableType(reference, out var genType, out _) && genType is GenerateType.Object or GenerateType.VersionTolerant or GenerateType.CircularReference)
                    ? "WritePackable"
                    : "WriteValue";
                return $"                    case {x.Tag}: writer.{method}(System.Runtime.CompilerServices.Unsafe.As<{symbolFullQualified}?, {ToUnionTagTypeFullyQualifiedToString(x.Type)}>(ref value)); break;";
            })
            .NewLine();

        return $$"""
            if (value == null)
            {
                writer.WriteNullUnionHeader();
{{OnSerialized.Select(x => "            " + x.Emit()).NewLine()}}
                return;
            }

            if (__typeToTag.TryGetValue(value.GetType(), out var tag))
            {
                writer.WriteUnionHeader(tag);

                switch (tag)
                {
{{writeBody}}
                    default:
                        break;
                }
            }
            else
            {
                SharpPackSerializationException.ThrowNotFoundInUnionType(value.GetType(), typeof({{symbolFullQualified}}));
            }
""";
    }

    string EmitUnionDeserializeBody()
    {
        var symbolFullQualified = ToUnionTagTypeFullyQualifiedToString(Symbol);

        var readBody = UnionTags.Select(x =>
        {
            var tagTypeFullQualified = ToUnionTagTypeFullyQualifiedToString(x.Type);

            var method = (x.Type.TryGetSharpPackableType(reference, out var genType, out _) && genType is GenerateType.Object or GenerateType.VersionTolerant or GenerateType.CircularReference)
                ? "ReadPackable"
                : "ReadValue";

            var castString = method == "ReadPackable" && symbolFullQualified != tagTypeFullQualified
                ? $"({tagTypeFullQualified})"
                : "";

            return $$"""
                case {{x.Tag}}:
                    if (value is {{tagTypeFullQualified}})
                    {
                        reader.{{method}}(ref System.Runtime.CompilerServices.Unsafe.As<{{symbolFullQualified}}?, {{tagTypeFullQualified}}>(ref value));
                    }
                    else
                    {
                        value = {{castString}}reader.{{method}}<{{tagTypeFullQualified}}>();
                    }
                    break;
""";
        }).NewLine();


        return $$"""
            if (!reader.TryReadUnionHeader(out var tag))
            {
                value = default;
{{OnDeserialized.Select(x => "                " + x.Emit()).NewLine()}}
                return;
            }

            switch (tag)
            {
{{readBody}}
                default:
                    SharpPackSerializationException.ThrowInvalidTag(tag, typeof({{symbolFullQualified}}));
                    break;
            }
""";
    }

    string EmitGenericCollectionTemplate(IGeneratorContext context)
    {
        var (collectionKind, collectionSymbol) = ParseCollectionKind(Symbol, reference);
        var methodName = collectionKind switch
        {
            CollectionKind.Collection => "Collection",
            CollectionKind.Set => "Set",
            CollectionKind.Dictionary => "Dictionary",
            _ => "",
        };

        var typeArgs = string.Join(", ", collectionSymbol!.TypeArguments.Select(x => x.FullyQualifiedToString()));

        var contextFormatterType = methodName switch
        {
            "Collection" => $"global::SharpPack.Formatters.GenericCollectionFormatter<{TypeName}, {typeArgs}>",
            "Set" => $"global::SharpPack.Formatters.GenericSetFormatter<{TypeName}, {typeArgs}>",
            "Dictionary" => $"global::SharpPack.Formatters.GenericDictionaryFormatter<{TypeName}, {typeArgs}>",
            _ => throw new InvalidOperationException(),
        };
        var contextFactoryInterface =
            $"global::SharpPack.ISharpPackFormatterFactory<{TypeName}>";
        var contextFactoryMethod = $$"""

    [global::SharpPack.Internal.Preserve]
    static global::SharpPack.SharpPackFormatter<{{TypeName}}> global::SharpPack.ISharpPackFormatterFactory<{{TypeName}}>.CreateFormatter()
    {
        return new {{contextFormatterType}}();
    }
""";

        var code = $$"""
partial class {{TypeName}} : {{contextFactoryInterface}}
{
    static partial void StaticConstructor();

    static {{Symbol.Name}}()
    {
        StaticConstructor();
    }
{{contextFactoryMethod}}
}
""";

        return code;
    }
}

public partial class MethodMeta
{
    public string Emit()
    {
        var instance = (IsStatic) ? ""
            : (IsValueType) ? "value."
            : "value?.";

        if (UseReaderArgument)
        {
            return $"{instance}{Name}(ref reader, ref value);";
        }
        else if (UseWriterArgument)
        {
            return $"{instance}{Name}(ref writer, ref value);";
        }
        else
        {
            return $"{instance}{Name}();";
        }
    }
}

public partial class MemberMeta
{
    public string EmitSerialize(
        string writer,
        bool honorFormatterOverrides = false)
    {
        if (honorFormatterOverrides &&
            Kind is not MemberKind.Blank and not MemberKind.CustomFormatter)
        {
            return $"{writer}.WriteValue(value.@{Name});";
        }

        switch (Kind)
        {
            case MemberKind.SharpPackable:
                return $"{writer}.WritePackable(value.@{Name});";
            case MemberKind.Unmanaged:
            case MemberKind.Enum:
                return $"{writer}.WriteUnmanaged(value.@{Name});";
            case MemberKind.UnmanagedNullable:
                return $"{writer}.DangerousWriteUnmanaged(value.@{Name});";
            case MemberKind.String:
                return $"{writer}.WriteString(value.@{Name});";
            case MemberKind.UnmanagedArray:
                return $"{writer}.WriteUnmanagedArray(value.@{Name});";
            case MemberKind.SharpPackableArray:
                return $"{writer}.WritePackableArray(value.@{Name});";
            case MemberKind.SharpPackableList:
                return $"global::SharpPack.Formatters.ListFormatter.SerializePackable(ref {writer}, value.@{Name});";
            case MemberKind.SharpPackableUnmanagedList:
                return $"global::SharpPack.Formatters.ListFormatter.SerializePackableUnmanaged(ref {writer}, value.@{Name});";
            case MemberKind.Array:
                return $"{writer}.WriteArray(value.@{Name});";
            case MemberKind.Blank:
                return "";
            case MemberKind.CustomFormatter:
                return $"{writer}.WriteValueWithFormatter(__{Name}Formatter, value.@{Name});";
            default:
                return $"{writer}.WriteValue(value.@{Name});";
        }
    }

    public string EmitVarIntLength()
    {
        switch (Kind)
        {
            case MemberKind.Unmanaged:
            case MemberKind.Enum:
            case MemberKind.UnmanagedNullable:
                return $"writer.WriteVarInt(System.Runtime.CompilerServices.Unsafe.SizeOf<{MemberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>());";
            case MemberKind.String:
                return $"writer.WriteVarInt(writer.GetStringWriteLength(value.@{Name}));";
            case MemberKind.UnmanagedArray:
                return $"writer.WriteVarInt(writer.GetUnmanageArrayWriteLength<{(MemberType as IArrayTypeSymbol)!.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(value.@{Name}));";
            case MemberKind.Blank:
                return $"writer.WriteVarInt(0);";
            default:
                throw new InvalidOperationException("This MemberKind is not supported, Kind:" + Kind);
        }
    }

    public string EmitReadToDeserialize(
        int i,
        bool requireDeltaCheck,
        bool honorFormatterOverrides = false)
    {
        var equalDefault = Kind == MemberKind.Blank
            ? "{ }"
            : $"{{ __{Name} = default; }}";

        var pre = requireDeltaCheck
            ? $"if (deltas[{i}] == 0) {equalDefault} else "
            : "";

        if (honorFormatterOverrides &&
            Kind is not MemberKind.Blank and not MemberKind.CustomFormatter)
        {
            return $"{pre}__{Name} = reader.ReadValue<{MemberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();";
        }

        switch (Kind)
        {
            case MemberKind.SharpPackable:
                return $"{pre}__{Name} = reader.ReadPackable<{MemberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();";
            case MemberKind.Unmanaged:
            case MemberKind.Enum:
                return $"{pre}reader.ReadUnmanaged(out __{Name});";
            case MemberKind.UnmanagedNullable:
                return $"{pre}reader.DangerousReadUnmanaged(out __{Name});";
            case MemberKind.String:
                return $"{pre}__{Name} = reader.ReadString();";
            case MemberKind.UnmanagedArray:
                return $"{pre}__{Name} = reader.ReadUnmanagedArray<{(MemberType as IArrayTypeSymbol)!.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();";
            case MemberKind.SharpPackableArray:
                return $"{pre}__{Name} = reader.ReadPackableArray<{(MemberType as IArrayTypeSymbol)!.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();";
            case MemberKind.SharpPackableList:
                return $"{pre}__{Name} = global::SharpPack.Formatters.ListFormatter.DeserializePackable<{(MemberType as INamedTypeSymbol)!.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(ref reader);";
            case MemberKind.SharpPackableUnmanagedList:
                return $"{pre}__{Name} = global::SharpPack.Formatters.ListFormatter.DeserializePackableUnmanaged<{(MemberType as INamedTypeSymbol)!.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(ref reader);";
            case MemberKind.Array:
                return $"{pre}__{Name} = reader.ReadArray<{(MemberType as IArrayTypeSymbol)!.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();";
            case MemberKind.Blank:
                return $"{pre}reader.Advance(deltas[{i}]);";
            case MemberKind.CustomFormatter:
                {
                    var mt = MemberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    return $"{pre}__{Name} = reader.ReadValueWithFormatter<{CustomFormatterName}, {mt}>(__{Name}Formatter);";
                }
            default:
                return $"{pre}__{Name} = reader.ReadValue<{MemberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();";
        }
    }

    public string EmitReadRefDeserialize(
        int i,
        bool requireDeltaCheck,
        bool honorFormatterOverrides = false)
    {
        var pre = requireDeltaCheck
            ? $"if (deltas[{i}] != 0) "
            : "";

        if (honorFormatterOverrides &&
            Kind is not MemberKind.Blank and not MemberKind.CustomFormatter)
        {
            return $"{pre}reader.ReadValue(ref __{Name});";
        }

        switch (Kind)
        {
            case MemberKind.SharpPackable:
                return $"{pre}reader.ReadPackable(ref __{Name});";
            case MemberKind.Unmanaged:
            case MemberKind.Enum:
                return $"{pre}reader.ReadUnmanaged(out __{Name});";
            case MemberKind.UnmanagedNullable:
                return $"{pre}reader.DangerousReadUnmanaged(out __{Name});";
            case MemberKind.String:
                return $"{pre}__{Name} = reader.ReadString();";
            case MemberKind.UnmanagedArray:
                return $"{pre}reader.ReadUnmanagedArray(ref __{Name});";
            case MemberKind.SharpPackableArray:
                return $"{pre}reader.ReadPackableArray(ref __{Name});";
            case MemberKind.SharpPackableList:
                return $"{pre}global::SharpPack.Formatters.ListFormatter.DeserializePackable(ref reader, ref __{Name});";
            case MemberKind.SharpPackableUnmanagedList:
                return $"{pre}global::SharpPack.Formatters.ListFormatter.DeserializePackableUnmanaged(ref reader, ref __{Name});";
            case MemberKind.Array:
                return $"{pre}reader.ReadArray(ref __{Name});";
            case MemberKind.Blank:
                return $"{pre}reader.Advance(deltas[{i}]);";
            case MemberKind.CustomFormatter:
                return $"{pre}reader.ReadValueWithFormatter(__{Name}Formatter, ref __{Name});";
            default:
                return $"{pre}reader.ReadValue(ref __{Name});";
        }
    }
}
