<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!-- <PublishAot>true</PublishAot> -->
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="SharpPackLogs\**" />
      <EmbeddedResource Remove="SharpPackLogs\**" />
      <None Remove="SharpPackLogs\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ConsoleAppFramework" Version="4.2.3" />
        <PackageReference Include="MessagePack" Version="3.1.8" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    </ItemGroup>

    <!-- output memoerypack serialization info to directory -->
    <ItemGroup>
        <CompilerVisibleProperty Include="SharpPackGenerator_SerializationInfoOutputDirectory" />
    </ItemGroup>
    <PropertyGroup>
        <SharpPackGenerator_SerializationInfoOutputDirectory>$(MSBuildProjectDirectory)\SharpPackLogs</SharpPackGenerator_SerializationInfoOutputDirectory>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\..\src\SharpPack.Core\SharpPack.Core.csproj" />
        <ProjectReference Include="..\..\src\SharpPack.Generator\SharpPack.Generator.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
        <ProjectReference Include="..\..\src\SharpPack.Streaming\SharpPack.Streaming.csproj" />
    </ItemGroup>

</Project>
